all: 
	gcc -o mandelbrot main.c file_operations.c mandelbrot_sec.c matriz_operations.c formato.h -lm
	gcc -o mandelbrotp main2.c file_operations.c mandelbrot_p.c matriz_operations.c formato.h -lm -fopenmp